# Goal
string text # Text to speak
string speaker # Speaker name for multi-speaker
string language # Language of the text. If None, the default language of the speaker is used. Language is only supported by `XTTS` model.
string speaker_wave # Path to a reference wav file to use for voice cloning with supporting models like YourTTS.
string emotion # Emotion to use for Coqui Studio models. If None, Studio models use "Neutral". Defaults to None.
float32 speed # Speed factor to use for Coqui Studio models, between 0 and 2.0. If None, Studio models use 1.0.

bool dont_split_sentences # Deactivate split text into sentences, synthesize them separately and concatenate the file audio.
# Setting it True uses more VRAM and possibly hit model specific text length or VRAM limits. Only
# applicable to the TTS models. 

float32 wait_before_speaking # Wait before speaking in seconds
# actual wait time is wait_before_speaking - generation time
# so if generation takes longer than we don't wait at all

---
# Result

bool success
string message # Error message

---
# Feedback

uint8 stage # One of the status codes below

uint8 STARTED=0            # Initial state
uint8 GENERATED_AUDIO=1    # Audio has been generated, waiting if needed
uint8 WAIT_DONE=2          # Audio starts playing
uint8 AUDIO_PLAYED=3       # Audio has finished playing